### PR TITLE
Bringing in stable develop into master

### PR DESCRIPTION
**Pull request by trevorforrey**

### CODE REVIEW

**Comment by swdunningASU** [comment]
Master does not seem to have the website.  The entire View directory is empty

**Comment by swdunningASU** [comment]
I was on the wrong branch, everything looks good!

**Comment by trevorforrey** [comment]
It looks good to me as well! Tested on develop heavily before making the video and theres only been readme changes since.

**Comment by PaHorton** [comment]
The web stuff looks fantastic and works as intended! Having tested it on develop I think it's ready for the big stage on master 🎉

**Comment by trevorforrey** [comment]
Merging in now!

**Pull request merged**
