### PR TITLE
Us 81 knowing user

### PR DESCRIPTION
**Pull request by trevorforrey**

### CODE REVIEW

**Comment by PaHorton** [comment]
Crashes when a username is set but a recipe is not selected. If a user does not follow the prompt for their recipe then when the setup-intent it will find session-data but will attempt to access an unknown parameter recipe.

**Comment by trevorforrey** [comment]
How would a user not follow the prompt for the recipe? Shouldn't it only progress if it's given a valid recipe?

**Comment by PaHorton** [comment]
Follow up's are optional in Dialogflow. The next step in the follow up may be to select a recipe but if I say something that triggers a different intent it'll back me out of that.

**Comment by trevorforrey** [comment]
Looks good. I always trust an engineer that approves their own stuff. 👺

**Comment by swdunningASU** [comment]
Looks good

**Pull request merged**
