### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by raisa-khatun**

### CODE REVIEW

**Comment by trevorforrey** [comment]
Looks good! Just remember to add the hotfix! After that comes in I'll be able to approve the pull request.

**Comment by swdunningASU** [comment]
Reviewed Front end and all the front end website stuff seems to be working as expected.   The cookbook needs to be updated after selecting a new recipe.  That's been done locally, but as soon as that has been done the pull request can be re-reviewed and merged.

**Comment by raisa-khatun** [comment]
All of my code looks good.

**Comment by trevorforrey** [comment]
David's new code works great. Made a small fix with ingredients / steps being appended and not deleted->appended when switching recipes. 

Cooking page looks good to me right now!

**Comment by swdunningASU** [comment]
The cookbook page seems to be working as intended and did not break anything else that I saw.

**Comment by trevorforrey** [comment]
As most people have reviewed and OK'd the PR, I'll be merging this into dev now! Great work team!

**Pull request merged**
